scraper:
  base_url: "https://www.gutenberg.org"
  start_path: "/ebooks/search/?sort_order=downloads"
  max_pages: 15
minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_raw: "raw"
  bucket_gold: "gold"