version: '3.8'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  airflow-webserver:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__PARALLELISM=2
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS=1
      - OPENLINEAGE_DISABLED="false"
      - OPENLINEAGE_CONFIG=/opt/airflow/sample_config/openlineage.yaml
      - OPENLINEAGE_PRODUCER=https://github.com/OpenLineage/OpenLineage
      - OPENLINEAGE_AIRFLOW_DISABLE_FORK=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sample_config:/opt/airflow/sample_config
      - ./.env:/opt/airflow/.env
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./requirements-airflow.txt:/opt/airflow/requirements-airflow.txt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: >
        bash -c "pip install --no-cache-dir -r /opt/airflow/requirements-airflow.txt &&
                 airflow db migrate &&
                 airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
                 airflow webserver --port 8080"
  airflow-scheduler:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - OPENLINEAGE_DISABLED="false"
      - OPENLINEAGE_CONFIG=/opt/airflow/sample_config/openlineage.yaml
      - OPENLINEAGE_PRODUCER=https://github.com/OpenLineage/OpenLineage
      - OPENLINEAGE_AIRFLOW_DISABLE_FORK=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sample_config:/opt/airflow/sample_config
      - ./.env:/opt/airflow/.env
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./requirements-airflow.txt:/opt/airflow/requirements-airflow.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
        bash -c "pip install --no-cache-dir -r /opt/airflow/requirements-airflow.txt &&
                 airflow scheduler"
  airflow-worker:
    image: apache/airflow:2.9.3
    restart: always
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - OPENLINEAGE_DISABLED="false"
      - OPENLINEAGE_CONFIG=/opt/airflow/sample_config/openlineage.yaml
      - OPENLINEAGE_PRODUCER=https://github.com/OpenLineage/OpenLineage
      - OPENLINEAGE_AIRFLOW_DISABLE_FORK=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sample_config:/opt/airflow/sample_config
      - ./.env:/opt/airflow/.env
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./requirements-airflow.txt:/opt/airflow/requirements-airflow.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
        bash -c "pip install --no-cache-dir -r /opt/airflow/requirements-airflow.txt &&
                 airflow celery worker"
    
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/app/src
  #     - ./.env:/app/.env
  #   command: uvicorn src.api:app --host 0.0.0.0 --port 8000
  #   depends_on:
  #     - minio
  #     - ollama
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   command: serve
  # pyspark:
  #   image: bitnami/spark:latest
  #   depends_on:
  #     minio:
  #       condition: service_healthy
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./src:/opt/spark/src
  #     - ./sample_config:/opt/spark/sample_config
  #     - ./.env:/opt/spark/.env
  #     - ./requirements-pyspark.txt:/opt/spark/requirements-pyspark.txt
  #     - ./data:/opt/spark/data 
  #   command: >
  #     bash -c "pip install --no-cache-dir -r /opt/spark/requirements-pyspark.txt &&
  #                 tail -f /dev/null"
  marquez-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=marquez
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
    volumes:
      - ./marquez_db_data:/var/lib/postgresql/data

  marquez:
    image: marquezproject/marquez:latest
    depends_on:
      - marquez-db
    restart: on-failure
    environment:
      - MARQUEZ_PORT=8080
      - MARQUEZ_ADMIN_PORT=8081
      - MARQUEZ_HOST=0.0.0.0
      - MARQUEZ_API_URL=http://localhost:8080/api/v1
      - MARQUEZ_CONFIG=/marquez.yml
      - MARQUEZ_MIGRATE_ON_STARTUP=true
      - JAVA_TOOL_OPTIONS=-Xms1g -Xmx2g -Djava.security.egd=file:/dev/./urandom
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
    - ./marquez.yml:/marquez.yml
    command: >
      bash -c "env && java -jar /marquez.jar"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/api/v1/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
  marquez-web:
    image: marquezproject/marquez-web:latest
    depends_on:
      - marquez
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=8080
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
  duckdb:
    image: python:3.10-slim
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./src:/app/src
      - ./sample_config:/app/sample_config
      - ./.env:/app/.env
      - ./requirements-duckdb.txt:/app/requirements-duckdb.txt
    stdin_open: true
    tty: true
    command: >
      bash -c "pip install --no-cache-dir -r /app/requirements-duckdb.txt &&
               tail -f /dev/null"
volumes:
  minio_data:
  postgres_data:
  redis_data:
  ollama_data:
  marquez_data: